name: Java CI

on:
  push:
    branches:
      - main  # Runs tests when code is pushed to 'main'
  pull_request:
    branches:
      - main  # Runs tests on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn clean test
